---
- name: Setup Hive with Postgres Metastore
  hosts: all
  become: yes

  vars:
    hive_home: /usr/local/hive
    spark_home: /usr/local/spark

  tasks:

    - name: Install required packages
      apt:
        name:
          - build-essential
          - postgresql-server-dev-all
          - acl
        state: present

    - name: Download Postgres Connector JAR
      get_url:
        url: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.0/postgresql-42.7.0.jar
        dest: /tmp/postgresql-42.7.0.jar

    - name: Copy Postgres Connector JAR to Hive lib directory
      copy:
        src: /tmp/postgresql-42.7.0.jar
        dest: "{{ hive_home }}/lib/postgresql-42.7.0.jar"
        remote_src: yes

    - name: Copy Postgres Connector JAR to Spark jars directory
      copy:
        src: /tmp/postgresql-42.7.0.jar
        dest: "{{ spark_home }}/jars/postgresql-42.7.0.jar"
        remote_src: yes

    - name: Ensure Hive configuration directory exists
      file:
        path: "{{ hive_home }}/conf"
        state: directory

    - name: Copy hive-default.xml.template to hive-site.xml
      command: cp hive-default.xml.template hive-site.xml
      args:
        chdir: "{{ hive_home }}/conf"

    - name: Upload Jinja2 template for hive-site.xml
      template:
        src: /Users/adixit/trino-build/roles/install/templates/hive-site.xml.j2
        dest: "{{ hive_home }}/conf/hive-site.xml"

    - name: Initialize Hive Metastore Schema
      command: "{{ hive_home }}/bin/schematool -dbType postgres -initSchema"
      args:
        chdir: "{{ hive_home }}/bin"
      register: init_metastore
      failed_when: "'ERROR' in init_metastore.stderr"

    - name: Grant permissions on schema public for Hive user
      become_user: postgres
      postgresql_db:
        name: hivemetastore
        state: present

    - name: Grant CREATE permission to Hive user
      postgresql_query:
        query: "GRANT CREATE ON SCHEMA public TO hiveuser;"
        db: hivemetastore

  handlers:
    - name: Restart Hive
      service:
        name: hive-server2
        state: restarted
